### ISSUE TITLE
The date widget is hidden under the markdown widget. Need to fix z index

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#43]
Example problem link

/DURC/requestlog/create

**Comment by kchapple** [comment]
@ftrotter I don't have that particular resource URL, but it appears to work in Inventory Transaction, unless I should be looking at a different widget.

![Screen Shot 2019-12-17 at 10 24 23 AM](https://user-images.githubusercontent.com/271809/71009109-b79f5d00-20b7-11ea-9065-4ae0dd6936f9.png)
