### ISSUE TITLE
Validation Layer At Model Level

### ISSUE THREAD

**Issue by kchapple** [CareSet/DURC#54]
Validator layer idea ->

Catch fields without defaults not being filled in.

Catch things you thought were numeric being filed in as string

Catch things you thought were integers that are actually decimal numbers

Catching strings that are longer than you made space for in the varchar

fields in the JSON that are not in the schema???

top level (i.e. not a subarray) that is not being filled in… generate a warning?

Cannot pass null to a non-nullable value.

**Comment by kchapple** [comment]
When running from command-line, this is what the validator should output on bad data.
<img width="862" alt="Screen Shot 2020-05-01 at 2 16 51 PM" src="https://user-images.githubusercontent.com/271809/80840805-1deecd00-8bcc-11ea-9910-a810b549fb79.png">

**Comment by seanccsmith** [comment]
Works perfectly.
