### ISSUE TITLE
Default Null fields and null checkbox require unchecking null to write

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#74]
The field should not be unwritable unless the 'null' is unchecked. 
It should be writeable, and by writing in it... the null gets unchecked. 

After writing in the text area... checking the null should popup a prompt that says "are you sure you want to erase what you have written but setting this field to null".

The current system works well enough, it just feels clumsy

**Comment by kchapple** [comment]
@ftrotter This has been done. Now you can just click in the text box to unlock the field.

<img width="1054" alt="Screen Shot 2020-09-22 at 1 27 16 PM" src="https://user-images.githubusercontent.com/271809/93916347-66bc3500-fcd7-11ea-902a-d66cca22c12a.png">

**Comment by ftrotter** [comment]
Excellent! I am assigning to @seanccsmith to review!

**Comment by seanccsmith** [comment]
@kchapple this is not working in LoreCommander. When I click the field, it does not allow me to write without first unticking the NULL box. I also can't make the pop-up appear.

**Comment by kchapple** [comment]
@seanccsmith the view doesn't have the new javascript. You may need to run mine and write

**Comment by kchapple** [comment]
Sorry, @seanccsmith I didn't check in the new models, controllers and views when I did these changes.

**Comment by seanccsmith** [comment]
@kchapple have they been checked in now? I ran a git pull on my DURC instance and then ran durc.php, but I'm not getting any different results.

**Comment by seanccsmith** [comment]
With the updated code, selecting a text box automatically unticks the null tickbox, and ticking it again prompts the pop-up.
