### ISSUE TITLE
Select field choice permenance.

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#76]
When you are first using a DURC form, the select2 magic makes it say things like the following in the select box

* Gengis Kahn (4)
* George Washington (3)
* Jon Doe (7)

But then when you select George Washington and you save the form.. what appears in the field the time is just 

* 3

It should still say "George Washington (3)" instead..

-ft

**Comment by kchapple** [comment]
@ftrotter This has been done.
![Screen Shot 2020-07-31 at 2 21 10 PM](https://user-images.githubusercontent.com/271809/89065085-1e1c7700-d339-11ea-91ea-be2fdfe6e379.png)

**Comment by seanccsmith** [comment]
This is working correctly.
