### ISSUE TITLE
Data is not saving on data server, with no error

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#77]
Internal careset system here: 
https://oner.set.care/DURC/userdetail/create?user_id=271809

Pressing save does not save the data, nor is an error returned. 

Do you have the ability to see this error Ken?

**Comment by kchapple** [comment]
This has been fixed, tested locally with OneR database @ftrotter

**Comment by seanccsmith** [comment]
Checkboxes seem to work no problem now.
