### ISSUE TITLE
Check instead of dropdown... 

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#81]
Instead of a dropdown with a list, instead I see a floating checkbox? Very weird.

<img width="1385" alt="check_bug" src="https://user-images.githubusercontent.com/83133/94069815-d2c19a80-fdb6-11ea-8011-002a4adff9b3.png">

**Comment by ftrotter** [comment]
Note that we updated the durc to the current master and retested... 

Now we have the problem with appealstate_id rather than primary_contact_person_id 

-ft

**Comment by kchapple** [comment]
@ftrotter This has been fixed. Now the select2 text will render with an error message (/jsonone endpoint returns a 401 Not Found status with error message) and we allow the user to make another selection, no longer breaks the select2 rendering.

<img width="1276" alt="Screen Shot 2020-09-25 at 1 33 48 PM" src="https://user-images.githubusercontent.com/271809/94298417-1b529280-ff34-11ea-82d4-cb1f0329560e.png">
<img width="1292" alt="Screen Shot 2020-09-25 at 1 33 57 PM" src="https://user-images.githubusercontent.com/271809/94298424-1d1c5600-ff34-11ea-8eb4-05cc4c0e2965.png">

**Comment by ftrotter** [comment]
This looks good. Switching assignment to Sean to confirm in testing..

**Comment by seanccsmith** [comment]
I'm unable to recreate this issue. Looks good.
