### ISSUE TITLE
DURC interface not saving

### ISSUE THREAD

**Issue by almatrotter** [CareSet/DURC#82]
Here is the url: https://foiagarden.set.care/DURC/nextaction/create

Pressing save here does not cause the "saved" alert, and also does not save the data.

**Comment by kchapple** [comment]
@ftrotter @almatrotter I pushed a fix for this. Fix is in the base DURC model class, so no need to re-run mine/write commands.

**Comment by seanccsmith** [comment]
This is working in LoreCommander and in FOIA Garden. Closing this issue.

However, I've uncovered a related issue, that there is no feedback given when a Save request is sent without specifying mandatory fields. #83
